### ISSUE TITLE
New theme setting for line-height

### ISSUE THREAD

**Issue by brunnopleffken** [adobe/brackets#11141]
Aside font size, I'd like to see another text field in Theme Settings: **line height**. It really helps to bring "air" to my code, specially with dark themes... Currently, I set my line height just like this:

```css
.CodeMirror-scroll {
    line-height: 1.6em !important;
}
```

I really wish it was a built-in preference, in Theme Settings.
