### ISSUE TITLE
Markdown highlighting doesn't work as it should

### ISSUE THREAD

**Issue by mkoske** [adobe/brackets#11691]
Hello,

I have been trying to ask this on IRC, but I'll write my question here too. 

So, why Markdown syntax highlighting is not working? In Codemirror, when you surround text with - for example - two asterisks to make text bold, it becomes bold, but when doing same in Brackets, it has no effect.

See Markdown-mode demo here:
http://codemirror.net/mode/markdown/index.html

I write a lot using Markdown and I would like to have proper syntax highlighting for it.

**Comment by redmunds** [comment]
You could create a Language in Brackets to use the CodeMirror mode, but I prefer using the Markdown Preview extension to see both the raw and formatted text at the same time.

**Comment by mkoske** [comment]
I got it partially solved by installing Brackets Themes -extension and choosing theme right theme. So it seems to be theme problem partially. But then, if I hard-wrap words, the highlighting breaks, at least with lists so it's not problem only with theme.

**Comment by petetnt** [comment]
I agree with @mkoske here, I wonder why Brackets doesn't add syntax highlighting to Markdown formatting when all the other Codemirror Markdown editors seem to do it? I use Markdown Preview too, but raw markdown should receive the syntax highlighting styles:

As in

`**hello world**` should show up in editor as 

![image](https://cloud.githubusercontent.com/assets/7641760/9836145/f1e114ca-5a16-11e5-8066-3fae5b8e0034.png)

instead of

![image](https://cloud.githubusercontent.com/assets/7641760/9836147/01f8bb42-5a17-11e5-8e78-a230a5edcacb.png)

**Comment by petetnt** [comment]
Oh, it's a bug:

See `brackets_codemirror_overrides.less`
``` css
/*
 * Temporarily override bold and italic syntax highlighting until
 * SourceCodePro supports them in a fixed pitch
 */
span.cm-em {
    font-style: normal;
}
span.cm-header, span.cm-strong {
    font-weight: normal;
}
span.cm-emstrong {
    font-style: normal;
    font-weight: normal;
}
```

Not sure if it has been fixed yet, the bolded letters seem to be very blurry but italics look okay?

![image](https://cloud.githubusercontent.com/assets/7641760/9836174/231b1616-5a18-11e5-8012-0ac436403592.png)
