### ISSUE TITLE
i am not able to get the border on buttons 

### ISSUE THREAD

**Issue by jub91** [adobe/brackets#13786]
```html
<html lang="en">
    <head>
        
        <link rel="stylesheet" type="text/css" href="vendors/css/normalize.css">
        <link rel="stylesheet" type="text/css" href="vendors/css/grid.css">
        <link rel="stylesheet" type="text/css" href="resources/css/style.css">
        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,300i,400" rel="stylesheet" type="text/css">
        <title>omnifood</title>
        
              </head>
    
    <body>
        <header>
            <div class="hero-text-box">
                <h1>Goodbye junk food.<br> Hello super healthy meals.</h1>
                <a class="btn btn-full" href="#">I’m hungry </a>
                <a  class="btn btn-" href="#">Show me more</a>
                
            
            
            
            
            
            </div>
        
        
        
        
        
        </header>
      
      </body>

</html>
```

css code

```css
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

html {
    background-color: #fff;
    color: #555;
    font-family: 'Lato','Arial',sans-serif;
    font-weight: 300;
    font-size: 20px;
    text-rendering: optimizeLegibility;
}

.row {
    max-width: 1140px;
    margin: 0 auto;
}

header{
    background-image: linear-gradient(rgba(0, 0, 0, 0.7),rgba(0, 0, 0, 0.7)),url(img/hero.jpg);
    background-size: cover;
   background-position: center;
     height:100vh;
}
.hero-text-box{
    position: absolute;
    width: 1140px;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
}

h1{
    margin: 0;
    color: #fff;
    font-size: 240%;
    font-weight: 300;
    text-transform: uppercase;
    letter-spacing: 1px;
    word-spacing: 4px;
}

.btn {
    display: inline-block;
    padding: 10px 30px;
    font-weight: 300;
    text-decoration: none;
}
```

![2017-10-22_08-22-06-f901199b0ce5bc273c516250d61bf3f7](https://user-images.githubusercontent.com/33014889/31871484-4ad6cda2-b7d2-11e7-9ba5-c093121de40a.png)
